# log group for cloudtrail
# This file contains the configuration for the CloudWatch log group
# that will be used to store the logs generated by AWS CloudTrail.
# The log group is named "/aws/cloudtrail/sttcast-access" and has a retention period of 14 days.
resource "aws_cloudwatch_log_group" "trail_logs" {
  name              = "/aws/cloudtrail/sttcast-access"
  retention_in_days = 14
}
