0: Héctor Socas
1: Héctor Vives
2: Sara Robisco
3: Francis Villatoro
4: María Ribes
5: Juan Carlos Gil
6: Gastón Giribet
7: Alberto Aparici
8: José Edelstein
9: Ángel López-Sánchez
10: Antonio Mampaso
11: José Miguel Mulet
12: Andrés Asensio
13: Estefanía Coluccio
14: Javier Atapuerca
15: José Alberto Rubiño
16: Almudena Castro
17: Juan Carlos Ortega
18: Isabel Cordero
19: Nacho Trujillo
20: Ignacio Crespo
21: Daniel Orts
22: Valentín Martínez Pillet
23: Javier Rodríguez Pacheco
24: Iván Martí Vidal
25: Marian Martínez
26: Sébastien Comerón
27: Jorge Martínez
28: Mireia Montes
29: Carlos Westendorp
