---
# app_exec - vars - main.yml

# Local dir
local_payload_dir: "/vagrant/Payload"

# Remote dir
remote_payload_dir: "{{ app_dir }}/Payload"
# remote_payload_dir: "{{ ram_mount_point }}/Payload"


# Configure sttcast
whmodel:    "small"
seconds:    "36000"
cpus:       "6"
min_offset: "60"
max_gap:    "0.8"
html_suffix: "whisper"
mp3_extension: ".mp3"
html_extension: "_{{ html_suffix }}.html"
audio_extension: "_{{ html_suffix }}_audio.html"
