---
# app_exec - vars - main.yml

# Local dir
local_payload_dir: "/vagrant/Payload"

# Remote dir
remote_payload_dir: "{{ app_dir }}/Payload"

# Configure sttcast
whmodel:    "small"
seconds:    "1800"
cpus:       "1"
min_offset: "60"
max_gap:    "0.8"
