---
# Install sttcast app


  - name: Sttcast directory
    file:
      path: "{{ app_dir }}"
      state: directory
      owner: ubuntu
    become: true

  - name: Clone Sttcast
    git:
      repo: "{{ app_repo }}"
      dest: "{{ app_dir }}"
  
  - name: Directory for Spanish vosk model
    file:
      path: "{{ vosk_model_dir }}"
      state: directory
      owner: ubuntu
    become: true

  # - name: Download Spanish voice model for vosk
  #   unarchive:
  #     src: https://alphacephei.com/vosk/models/vosk-model-es-0.42.zip
  #     dest: /mnt/vol/vosk-models/es
  #     remote_src: yes

  - name: Add deadsnakes repo
    apt_repository: 
      repo: ppa:deadsnakes/ppa
    become: true
 
  - name: Install dependencies
    apt:
      name: 
      - python{{ python_version }}
      - python3-boto3
      - python3-botocore
      - ffmpeg
      - awscli
      state: present
      update_cache: yes
    become: true

  - name: Install virtualenv
    pip:
      name:
        virtualenv
      virtualenv_python: /usr/bin/python{{ python_version }}

  - name: Install packages in virtual environment
    pip:
      name:
      - pyyaml
      - vosk
      - wave
      - bs4
      - botocore
      - boto3
      - git+{{ whisper_repo }}
      virtualenv: "{{ app_dir }}/.venv"
      virtualenv_python: "/usr/bin/python{{ python_version }}"
